apiVersion: v1
kind: Secret
metadata:
  name: swiftpay-secrets
type: Opaque
stringData:
  # Replace with Supabase pooler JDBC URL or in-cluster Postgres
  DB_URL: jdbc:postgresql://postgres:5432/swiftpay
  DB_USERNAME: postgres
  DB_PASSWORD: changeme
